GET https://localhost:7017/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCdWJlckRpbm5lciIsImlzcyI6IkJ1YmVyRGlubmVyIiwiZXhwIjoxNzQ2NzIxODIwLCJuYmYiOjE3NDY3MTgyMjAsInN1YiI6IjQ1OThiNzMwLTA4MWQtNDNhYi1hMTJlLTFlNmUxNDQ0ODc3YiIsImdpdmVuX25hbWUiOiJKb24iLCJmYW1pbHlfbmFtZSI6IkRvdWdsYXMiLCJqdGkiOiJlNTg4OTRkZC04NmQ5LTQ4OTEtOGUzNy1jNjRhOTljNDE1M2IiLCJpYXQiOjE3NDY3MTgyMjB9.l5_9yJovhDVbYvamMn763PhYpIEJYrBTbNBReZXN1sU
